### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [allenbui94/octojourney-deepgray#1]
you do not need to include `pg` package when including `pg-promise`, because `pg-promise` includes `pg` on its own ;)

**Comment by allenbui94** [comment]
Oh, thank you for letting me know!

**Comment by vitaly-t** [comment]
You are welcome!

And you are definitely not going to need `pg-query`, because `pg-promise` can do all that, only much better ;)

**Comment by allenbui94** [comment]
Gotcha. This is sort of my first delving into nodeJS so its awesome to hear from someone trying to help out. I've read a little bit about promises and they sound like the right thing to use -- they look really neat.

I'll go ahead and remove pg-query for now too then. Going to push it in the same commit I install express and passport, which I hope will get my app on the ground faster -- all I need is a front-end multipage MVC framework and I think that's it...

Again, thank you for helping me out!

**Comment by vitaly-t** [comment]
Again, you are welcome.

You can check out this article: [Designing a RESTful API With Node and Postgres](http://mherman.org/blog/2016/03/13/designing-a-restful-api-with-node-and-postgres)

**Comment by allenbui94** [comment]
I'll check it out, thanks!
